version: '3.8'
services:
  freecad:
    image: registry.mcdonaldkin.com/freecad-appimage
    container_name: freecad
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped
